### ISSUE TITLE
Does not handle semicolons in mixin parameter

### ISSUE THREAD

**Issue by DavidHavl** [gabteles/gulp-less2sass#1]
Hi there, 
firstly thank you for your good work.

This does not seem to handle a scenario where there is a semicolon in mixin parameter.
E.g.:

``` css
     .button-outline-variant(@color; @activeTextColor: #fff) {
       color: @color;
     }
```

A regex to take care of it could be something like this:

```
/;(?=((?!\().)*?\))/
```
